### ISSUE TITLE
2021_USTC_JointPhD - 人工智能系统实践 - 成果提交

### ISSUE THREAD

**Issue by IMSUVEN** [microsoft/AI-System#24]
本 issue 将作为2021_USTC_JointPhD-人工智能系统实践项目成果的提交地址
项目截止日期： **5月26日**  
请在**北京时间2021年5月27日17点前**，在本issue下提交你的成果。

提交步骤：
1. 创建公共仓库
请各位同学使用个人的Github账户创建名为`MSRA-USTC-AISystemProject-2021`的公开仓库
2. 上传成果
请各位同学按以下目录结构，将个人成果进行整理，**删去个人隐私信息**，并上传至第一步中创建的公开仓库中
```
# 实验1
|-- lab 1
    # 图片均放在images目录下
    |-- images
        |-- image1.png
        |-- image2.jpg
    # 代码均放在src目录下
    |-- src
        |-- code1.py
        |-- code2.ipynb
    # 其他文件均放在resources目录下
    |-- resources
    # 请在README.md中放置各个文件的内容说明，你的实验流程和成果展示
    |-- README.md
# 实验6
|-- lab 6
    |-- ...
```
3. 提交成果
按以下内容格式回复本issue，**请注意保护个人隐私**
```markdown
1. 报名时提供的邮件地址: yourmail[at]your.domain
2. 个人仓库地址: https://github.com/yourname/yourrepositories
3. 补充信息(可选)
```

有其他疑问的地方请随时与助教联系

**Comment by Rxsw** [comment]
1. 报名时提供的邮件地址:  rxsw@mail.ustc.edu.cn
2. 个人仓库地址: https://github.com/Rxsw/MSRA-USTC-AISystemProject-2021

**Comment by RabbitWhite1** [comment]
1. 报名时提供的邮件地址: wzh895650485@mail.ustc.edu.cn
2. 个人仓库地址: https://github.com/RabbitWhite1/MSRA-USTC-AISystemProject-2021

**Comment by Rxsw** [comment]
1. 报名时提供的邮件地址: rxsw@mail.ustc.edu.cn
2. 个人仓库地址: https://github.com/Rxsw/MSRA-USTC-AISystemProject-2021

**Comment by suyZhong** [comment]
1. 报名时提供的邮件地址: zhongsuyang@mail.ustc.edu.cn
2. 个人仓库地址： https://github.com/suyZhong/MSRA-USTC-AISystemProject-2021

**Comment by BC-Li** [comment]
1. 报名时提供的邮件地址: lazuliterabbit@mail.ustc.edu.cn
2. 个人仓库地址： https://github.com/BC-Li/MSRA-USTC-AISystemProject-2021

**Comment by Ivanfangsc** [comment]
1. 报名时提供的邮件地址: shuchengfang@mail.ustc.edu.cn
2. 个人仓库地址： https://github.com/Ivanfangsc/MSRA-USTC-AISystemProject-2021

**Comment by bingps** [comment]
1. 报名时提供的邮件地址: liuguangda@mail.ustc.edu.cn
2. 个人仓库地址: https://github.com/bingps/MSRA-USTC-AISystemProject-2021

**Comment by TobeyQin** [comment]
感谢大家及时提交实践项目，我们会尽快给大家结果反馈！
