### ISSUE TITLE
README.md中，关于“A-基础教程”的超链接失效

### ISSUE THREAD

**Issue by tanghuanoo** [microsoft/AI-System#242]
README.md中，关于“A-基础教程”的超链接失效。

![image](https://user-images.githubusercontent.com/13616966/233275578-11ecd263-897c-40f2-b1ee-4eb988c0c8a8.png)

看起来应该是：
```
https://github.com/microsoft/ai-edu/tree/master/%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B
```
![image](https://user-images.githubusercontent.com/13616966/233275760-ebc8d80c-c26f-43b9-8433-6756bedfbb8b.png)

**Comment by YanjieGao** [comment]
fixed
