### ISSUE TITLE
An Error by Lecture 3 - Computation frameworks for DNN

### ISSUE THREAD

**Issue by Vincenwwx** [microsoft/AI-System#35]
In page 19 by calculation of the gradient of L(x), there is probably an error in the second part for **sin(exp(x)+exp(x)^2**

Should the gradient be cos(exp(x)+exp(x)^2)(exp(x)+2exp(x)^2), i.e. there is one unnecessary exp in the answer?

Thanks

**Comment by BC-Li** [comment]
Hi Wenxin, 

I opened a pull request #37 to change the formula.

Thanks for the issue!
