### ISSUE TITLE
Lack part of contents at chapter 2

### ISSUE THREAD

**Issue by YanjieGao** [microsoft/AI-System#53]
Dear Xiaowu哥,

Seems Chapter 2 lacks some content below. Will add it in the later version? 

2.2 深度学习系统基础
2.2.1 深度学习运算的表示
2.2.2 编译框架与中间表达
2.2.3 运行态和硬件
2.2.4 分布式执行
2.2.5 深度学习系统性能优化

**Comment by xiaowuhu** [comment]
Yanjie，我以为第二章是在讲深度学习的基本知识，而不是深度学习系统的基本知识，这两个差异很大，而且我不具备写上述章节的能力。
我感觉 “深度学习系统的基本知识” 可以单起一章来写。

**Comment by YanjieGao** [comment]
@jlxue Hi Jilong & Xiaowu @xiaowuhu ，看起来2.2可以和chapter3和4合并？或者作为chapter 3 的一个sub chapter只需要一个文件串起一个example? Jilong觉得呢？

**Comment by YanjieGao** [comment]
@xiaowuhu @jlxue  After sync, Jilong will take these (2.2) and reorg the outline of this part content. Thank you all!

**Comment by xiaowuhu** [comment]
cool! thanks Jilong! 第二章已经很长了，是应该放到第三章里。
