### ISSUE TITLE
Content in Security

### ISSUE THREAD

**Issue by YanjieGao** [microsoft/AI-System#99]
Dear Xian and Peichen,

我们可以在安全章节添加总览内容并展开到各章吗？例如课程中这两张图分别放入内容。统揽全局
![image](https://user-images.githubusercontent.com/5576848/167800317-2ae9a22e-0887-4489-9a33-92ef48266bd9.png)

![image](https://user-images.githubusercontent.com/5576848/167800271-e9502cde-b92f-4e74-9c50-5da2f05c79fc.png)

**Comment by YanjieGao** [comment]
NVIDIA H100已经在硬件层加入隐私计算功能说明越来越重要，可否适当补充这块相关内容，在软硬件层。

**Comment by peichenxie** [comment]
是不是可以将现在的12.1和12.2合并成一节，叫12.1深度学习内在的安全问题；然后把和defence、系统相关的内容单独组成一节，叫12.2隐私保护深度学习系统？

**Comment by YanjieGao** [comment]
章节可以调的。只保留两节，会不会单小节内容过多？也可以考虑拆的操作？保持章节内容量相对均匀些，例如 系统的有两小节，前面的有两小节？。

**Comment by YanjieGao** [comment]
目前7章已经拆成6,7小节了。感觉拆是不是更方便些？甚至可以有小节叫隐私硬件

**Comment by peichenxie** [comment]
> 章节可以调的。只保留两节，会不会单小节内容过多？也可以考虑拆的操作？保持章节内容量相对均匀些，例如 系统的有两小节，前面的有两小节？。

应该不会，基本上只是把现有内容重新组织一下

**Comment by YanjieGao** [comment]
好的，调整吧

**Comment by zhxianlucky** [comment]
关于章节调整以及加nvdia硬件的内容我都没有问题哈，peichen你可以直接在内容上做修改，改完了我们再看哪些内容需要扩充。
关于加ppt里的两张图，我在12.1.2里放过一个很类似的图，我可以想想怎么和yanjie你表达的这个意思合并一下。

**Comment by YanjieGao** [comment]
好的Xian，可以在12.1.2的图中框出对应的问题序号或者问题哈。这样方便读者对应上是哪个位置出问题哈。

**Comment by YanjieGao** [comment]
当前章节内容很多部分感觉还可以展开多说说哈，安全领域非常重要。感觉可以多说些哈。

**Comment by YanjieGao** [comment]
Dear Xian and Peichen， 除了研究工作，如果当前有主流开源系统或者开源框架和硬件中支持的安全特性，也请加入与总结，方便读者参考使用。


https://github.com/microsoft/AI-System/blob/main/Textbook/%E7%AC%AC8%E7%AB%A0-%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E6%8E%A8%E7%90%86%E7%B3%BB%E7%BB%9F/8.4-%E9%83%A8%E7%BD%B2.md#847-%E4%BB%A3%E8%A1%A8%E6%80%A7%E6%8E%A8%E7%90%86%E7%B3%BB%E7%BB%9F
